version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    container_name: speakx_db
    environment:
      POSTGRES_USER: speakx_admin
      POSTGRES_PASSWORD: speakx_password
      POSTGRES_DB: speakx_pro
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
