"""Initial schema

Revision ID: 28f18348741c
Revises: 
Create Date: 2026-08-05 05:16:58.529199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '28f18348741c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('student', 'faculty', 'admin', 'super_admin', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_history_created_at'), 'chat_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_history_id'), 'chat_history', ['id'], unique=False)
    op.create_index(op.f('ix_chat_history_user_id'), 'chat_history', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('video_filename', sa.Text(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('wpm', sa.Integer(), nullable=True),
    sa.Column('fillers', sa.Integer(), nullable=True),
    sa.Column('fillers_per_minute', sa.Float(), nullable=True),
    sa.Column('num_pauses', sa.Integer(), nullable=True),
    sa.Column('avg_pause_sec', sa.Float(), nullable=True),
    sa.Column('total_pause_sec', sa.Float(), nullable=True),
    sa.Column('mean_pitch_hz', sa.Float(), nullable=True),
    sa.Column('pitch_variation_hz', sa.Float(), nullable=True),
    sa.Column('eye_contact_pct', sa.Float(), nullable=True),
    sa.Column('head_pose_forward_pct', sa.Float(), nullable=True),
    sa.Column('head_pose_dominant', sa.String(length=20), nullable=True),
    sa.Column('posture_upright_pct', sa.Float(), nullable=True),
    sa.Column('posture_dominant', sa.String(length=20), nullable=True),
    sa.Column('gesture_active_pct', sa.Float(), nullable=True),
    sa.Column('smile_pct', sa.Float(), nullable=True),
    sa.Column('readability', sa.String(length=50), nullable=True),
    sa.Column('grade_level', sa.String(length=20), nullable=True),
    sa.Column('reading_ease', sa.Float(), nullable=True),
    sa.Column('vocabulary_ttr', sa.Float(), nullable=True),
    sa.Column('coherence_score', sa.Float(), nullable=True),
    sa.Column('total_sentences', sa.Integer(), nullable=True),
    sa.Column('avg_sentence_length', sa.Float(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('llm_report', sa.Text(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_session_date'), 'sessions', ['session_date'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('session_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_embeddings_id'), 'session_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_session_embeddings_user_id'), 'session_embeddings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_embeddings_user_id'), table_name='session_embeddings')
    op.drop_index(op.f('ix_session_embeddings_id'), table_name='session_embeddings')
    op.drop_table('session_embeddings')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_date'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_chat_history_user_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_created_at'), table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
